apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thisapp
  template:
    metadata:
      labels:
        app: thisapp
    spec:
      containers:   
      - name: devopsx-container
        image: strudelhund69/devopsx:version2
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: thisapp-service
spec:
  selector:
    app: thisapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # Expose the service on a port of the nodes

  ---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60