# Stage 1: Build the application
FROM node:18 AS builder

# Set the working directory in the container
RUN ls
RUN echo "vor WORKDIR /app"
WORKDIR /app

# Copy package.json and package-lock.json
RUN ls
RUN echo "vor copy package*.json ./"
COPY package*.json ./

# Install dependencies
RUN ls
RUN echo "vor npm install"
RUN npm install

# Copy the entire Next.js project to the container
RUN ls
RUN echo "vor COPY .."
COPY . .

# Build the Next.js application
RUN ls
RUN echo "vor npm run build"
RUN npm run build

# Stage 2: Create the production image
FROM node:18

# Set the working directory in the final container
WORKDIR /app

# Copy only the necessary files from the first stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public

# Expose the application's port (change it if your app uses a different port)
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]
